### ISSUE TITLE
knife opc org user add ORG_NAME USER_NAME with --admin flag in 409 case

### ISSUE THREAD

**Issue by tylercloke** [chef/knife-opc#31]
### Bug

If a user is already associated, and you say:

`knife opc org user add ORG_NAME USER_NAME`

It will properly output:

```
User rainbowdash already associated with organization ponyville
```

But if you add the `--admin` flag:

`knife opc org user add ORG_NAME USER_NAME --admin`

You get:

```
User rainbowdash already associated with organization ponyville
ERROR: knife encountered an unexpected error
This may be a bug in the 'opc org user add' knife command or plugin
Please collect the output of this command with the `-VV` option before filing a bug report.
Exception: NoMethodError: undefined method `add_user_to_group' for #<Chef::Org:0x00000000f94ef8>
```

### Reason

This occurs because [this block of code](https://github.com/chef/knife-opc/blob/master/lib/chef/knife/opc_org_user_add.rb#L54-L57) will still get executed in the 409 case, even though `org` is `nil`. We should change execution flow to avoid hitting that block in the 409 case.

### Full output

```
# chef-server-ctl org-user-add ponyville rainbowdash --admin -VV
INFO: Using configuration from /etc/opscode/pivotal.rb
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::JSONToModelOutput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_request
DEBUG: Signing the request as pivotal
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_request
DEBUG: Initiating POST to https://127.0.0.1/organizations/ponyville/association_requests
DEBUG: ---- HTTP Request Header Data: ----
DEBUG: Content-Type: application/json
DEBUG: Accept: application/json
DEBUG: Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
DEBUG: X-OPS-SIGN: algorithm=sha1;version=1.0;
DEBUG: X-OPS-USERID: pivotal
DEBUG: X-OPS-TIMESTAMP: 2015-04-20T22:03:47Z
DEBUG: X-OPS-CONTENT-HASH: t4LpIfJ2CS7wuSMGPK7ZUbCZko0=
DEBUG: X-OPS-AUTHORIZATION-1: wF3qjPS0RC1pTjrRndzhnNV9DvDarCKTbnxx8WthgnkGm3vdWbsa/qFTgyAQ
DEBUG: X-OPS-AUTHORIZATION-2: Ob5x+46xHyXBWGa2k48c4etjdKNdZ+QPfYNgPQ4Nork86GaWjZnhVCB0oyvd
DEBUG: X-OPS-AUTHORIZATION-3: 6Ee5WfTIPiMX3xOFDXBKmnwDaLPyDuvPsIyAWj7MzTLXH4oDpxvWsOolc2uu
DEBUG: X-OPS-AUTHORIZATION-4: 0ujPekTE7mZBuMV2szIs+tHH/m4aelaZ+Qn11uStIgwMnZcIg+qKoGR78uoo
DEBUG: X-OPS-AUTHORIZATION-5: 3tEAMNrsYZCo0kmsr8119pwqB0QZIytBtjDpmHEZCZu4o5AmVwU+0m7xvBJ/
DEBUG: X-OPS-AUTHORIZATION-6: ry/cfXErKhLgglDOq3GFAXXA0rwvp9YzhqWQgyWmSg==
DEBUG: HOST: 127.0.0.1:443
DEBUG: X-REMOTE-REQUEST-ID: c8fa6107-af99-4c88-a80b-b1454146569d
DEBUG: Content-Length: 22
DEBUG: ---- End HTTP Request Header Data ----
DEBUG: ---- HTTP Status and Header Data: ----
DEBUG: HTTP 1.1 409 Conflict
DEBUG: server: openresty/1.7.10.1
DEBUG: date: Mon, 20 Apr 2015 22:03:47 GMT
DEBUG: content-type: application/json
DEBUG: content-length: 43
DEBUG: connection: close
DEBUG: x-ops-api-info: flavor=cs;version=12.0.0;oc_erchef=1.6.4
DEBUG: location: http://127.0.0.1/organizations/ponyville/association_requests/invalid_path
DEBUG: ---- End HTTP Status/Header Data ----
DEBUG: ---- HTTP Response Body ----
DEBUG: {"error":"The association already exists."}
DEBUG: ---- End HTTP Response Body -----
DEBUG: ---- HTTP Request Body ----
DEBUG: {"user":"rainbowdash"}
DEBUG: ---- End HTTP Request Body ----
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_response
DEBUG: Content-Length validated correctly.
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONToModelOutput#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_response
INFO: HTTP Request Returned 409 Conflict: The association already exists.
User rainbowdash already associated with organization ponyville
/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/knife-opc-0.3.0/lib/chef/knife/opc_org_user_add.rb:54:in `run': undefined method `add_user_to_group' for #<Chef::Org:0x00000001e26368> (NoMethodError)
	from /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.3.0.dev.0/lib/chef/knife.rb:422:in `block in run_with_pretty_exceptions'
	from /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.3.0.dev.0/lib/chef/local_mode.rb:39:in `with_server_connectivity'
	from /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.3.0.dev.0/lib/chef/knife.rb:421:in `run_with_pretty_exceptions'
	from /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.3.0.dev.0/lib/chef/knife.rb:214:in `run'
	from /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.3.0.dev.0/lib/chef/application/knife.rb:142:in `run'
	from /opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.3.0.dev.0/bin/knife:25:in `<top (required)>'
	from /opt/opscode/embedded/bin/knife:23:in `load'
	from /opt/opscode/embedded/bin/knife:23:in `<main>'
```

**Comment by tylercloke** [comment]
This is fixed in current patch.
